### PR TITLE
experimenting with getting travis happier with racket

### PR DESCRIPTION
**Pull request by zenspider**

### CODE REVIEW

**Comment by kytrinyx** [comment]
It passed. Is that a good sign? Or has this been seemingly non-deterministic?

**Comment by yurrriq** [comment]
Relevant: https://twitter.com/arrdem/status/764151041604542464

**Comment by zenspider** [comment]
@kytrinyx one of our PRs uses a library only available in a newer racket... so I had to submit a PR to greghendershot/travis-racket to get that updated (and overhauled it while I was in there). This should allow me to rebase our PR against this to get it green.

**Comment by yurrriq** [comment]
Awesome! Thanks for all your work on this, @zenspider.

**Pull request merged**
