### PR TITLE
Add acronym exercise

### PR DESCRIPTION
**Pull request by tautologico**
This patch adds the acronym exercise with stub, tests and an example solution, as per the guidelines. The tests were based on the x-common test data.

### CODE REVIEW

**Comment by tautologico** [comment]
So, what's the next step here?

**Comment by tautologico** [comment]
Sorry for the noise, I deleted the branch from my repo and didn't realize it would affect the PR.

**Comment by yurrriq** [comment]
After a quick glance on my phone, this looks good to me. /ping @arguello

**Comment by yurrriq** [comment]
Merging. We can always update it later. Thanks, @tautologico!

**Pull request merged**
