### PR TITLE
Add grep exercise

### PR DESCRIPTION
**Pull request by bennn**
Now with an updated `config.json` and `module+ test`.

### CODE REVIEW

**Comment by arguello** [comment]
Looks good, thank you!

**Comment by kytrinyx** [comment]
I just realized that we don't have the metadata for the `grep` exercise: https://github.com/exercism/x-common

I wrote up a bit about how to add a completely new problem: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#submitting-new-problems

Would one of you mind adding the `.md` and `.yml` file for grep in x-common, please?

**Comment by bennn** [comment]
Sure

**Comment by bennn** [comment]
https://github.com/exercism/x-common/pull/106

**Comment by kytrinyx** [comment]
Perfect, thanks!

**Pull request merged**
