### PR TITLE
Put exercises into a logical order

### PR DESCRIPTION
**Pull request by mbertheau**
I tried to come up with a logical order of exercises. This is what I ended up with.

I changed the order on https://github.com/exercism/xracket/wiki/Order-of-exercises as well to reflect.

### CODE REVIEW

**Comment by arguello** [comment]
Looks good - thanks!

@yurrriq - what do you think?

**Comment by yurrriq** [comment]
Maybe swap rna-transcription and anagram so hamming and rna-transcription are back-to-back. Otherwise it's hard to argue with the logic here. I like the categorizing in the wiki.

**Comment by mbertheau** [comment]
I put anagram between the two for students that grew tired of dna and rna. I can see however how passion goes both ways :)

@arguello - your call :)

**Comment by yurrriq** [comment]
"If it ain't broke, don't fix it." LGTM

**Comment by arguello** [comment]
cool

**Comment by wobh** [comment]
Two resources I find myself referring to often:

- all exercises implemented by language: http://synopsis.exercism.io
- all exercise readme's: https://github.com/exercism/x-common

I've been wondering about organizing exercises into one or more trees by themes, topics, and maybe even characters, situations, or subjects.

**Comment by kytrinyx** [comment]
@wobh did I link you to this discussion? https://github.com/exercism/x-common/issues/63

**Comment by kytrinyx** [comment]
Also worth noting: there's a "todo" keyword in the problems api: http://x.exercism.io/tracks/racket

**Pull request merged**
