### PR TITLE
Meetup exercise

### PR DESCRIPTION
**Pull request by mbertheau**

### CODE REVIEW

**Comment by yurrriq** [comment]
Can you isolate the meetup exercise in this PR?

**Comment by mbertheau** [comment]
I'll wait for what happens with #4 with this.

**Comment by yurrriq** [comment]
@arguello, what are you thoughts on `1st` vs `first` etc?

**Comment by yurrriq** [comment]
Sounds good. I'll merge after that.

**Comment by yurrriq** [comment]
I love the inclusion of `leap-year?` by the way.

**Comment by mbertheau** [comment]
Now it's only the exercise :)

**Comment by yurrriq** [comment]
Looks good. Can you move the trailing parens on [meetup/example.rkt:45](https://github.com/mbertheau/xracket/blob/e5b98b82af6ae5af1e982c40dc5a8eadeab34bd1/meetup/example.rkt#L45) to the previous line? It's nitpicky, but I would make a similar nitpick on the site ha

**Comment by arguello** [comment]
The tests fail for me:

```
Testing meetup...
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:14:4
actual:     (date* 0 0 19 13 5 2013 1 132 #t -18000 0 "CDT")
expected:   (date* 0 0 19 12 5 2013 0 131 #t -18000 0 "CDT")
Check failure
--------------------
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:15:4
actual:     (date* 0 0 18 16 2 2013 6 46 #f -21600 0 "CST")
expected:   (date* 0 0 18 15 2 2013 5 45 #f -21600 0 "CST")
Check failure
--------------------
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:16:4
actual:     (date* 0 0 19 30 4 2013 2 119 #t -18000 0 "CDT")
expected:   (date* 0 0 19 6 5 2013 1 125 #t -18000 0 "CDT")
Check failure
--------------------
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:17:4
actual:     (date* 0 0 19 8 4 2013 1 97 #t -18000 0 "CDT")
expected:   (date* 0 0 19 7 4 2013 0 96 #t -18000 0 "CDT")
Check failure
--------------------
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:18:4
actual:     (date* 0 0 19 19 9 2013 4 261 #t -18000 0 "CDT")
expected:   (date* 0 0 19 18 9 2013 3 260 #t -18000 0 "CDT")
Check failure
--------------------
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:19:4
actual:     (date* 0 0 19 24 3 2013 0 82 #t -18000 0 "CDT")
expected:   (date* 0 0 19 23 3 2013 6 81 #t -18000 0 "CDT")
Check failure
--------------------
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:20:4
actual:     (date* 0 0 19 24 10 2013 4 296 #t -18000 0 "CDT")
expected:   (date* 0 0 19 30 10 2013 3 302 #t -18000 0 "CDT")
Check failure
--------------------
--------------------
Tests for the meetup exercise > #f
Unnamed test
FAILURE
name:       check-equal?
location:   meetup-test.rkt:21:4
actual:     (date* 0 0 18 22 2 2012 3 52 #f -21600 0 "CST")
expected:   (date* 0 0 18 28 2 2012 2 58 #f -21600 0 "CST")
Check failure
--------------------
0 success(es) 8 failure(s) 0 error(s) 8 test(s) run
```

**Comment by mbertheau** [comment]
Interesting. Maybe a timezone problem. Will investigate.

**Comment by yurrriq** [comment]
After a quick glance, should `first-of-week` on [line 44](https://github.com/mbertheau/xracket/blob/e5b98b82af6ae5af1e982c40dc5a8eadeab34bd1/meetup/example.rkt#L44) be `1` instead? Sorry if that's misguided, but I remember a similar issue in a different language.

**Comment by mbertheau** [comment]
Reproduce with
```
TZ=America/Chicago bin/check-exercises.sh
```

Before fixing the dependency I need to make the test fail on travis as well.

**Comment by mbertheau** [comment]
I.e. the test doesn't fail on travis: https://travis-ci.org/mbertheau/xracket/builds/76335733

**Comment by yurrriq** [comment]
Ah, good call. Thanks for all your work on this, by the way.

**Pull request merged**
