### PR TITLE
Added first pass at allergies problem.

### PR DESCRIPTION
**Pull request by zenspider**
Not thrilled with the way that testing is done in exercism for racket...
I've moved a number of tests over to test-case + check-true/false and
refactored into lists-equiv? that uses check-equal?. Revamping the other
tests will come some other time.

### CODE REVIEW

**Comment by zenspider** [comment]
I did a force push but the CI never bothered to re-run. Works fine in circleci, but not in travis, I guess. There is no re-run button that I know of. The tests pass just fine.

**Comment by kytrinyx** [comment]
@exercism/lisp Would one of you have a moment to review this, please?

@zenspider I'll kick off CI (weird, that usually works on force push).

**Comment by kytrinyx** [comment]
Restarted CI.

**Comment by yurrriq** [comment]
LGTM though it looks like Travis is angry.

**Comment by zenspider** [comment]
Hrm. Travis is full of shit. Look at my diff vs its error. Clearly not running the right thing.

I've had much better experiences with circleci for this very type of reason.

**Comment by zenspider** [comment]
Yeah. Those hashes don't match up.

@kytrinyx suggestions?

**Comment by yurrriq** [comment]
I think we should run the configlet stuff before check-exercises. `bin/check-exercises.sh` moves files around, so maybe it didn't clean up after itself.

**Comment by yurrriq** [comment]
FWIW `./bin/check-exercises.sh` doesn't work for me locally on macOS 10.11.6 with Racket 6.6.

Each test complains:
> find-exe: can't find Racket executable for variant 3m

And then all the tests fail:
> 21/21 test failures

**Comment by zenspider** [comment]
```
10004 % git checkout add/allergies 
Switched to branch 'add/allergies'
10007 % git clean -fd
Removing exercises/allergies/allergies.rkt
Removing exercises/meetup/
10009 % ./bin/check-exercises.sh
/Users/ryan/Work/git/zenspider/xracket/exercises
raco test: 0 (submod "./accumulate/accumulate-test.rkt" test)
raco test: 1 (submod "./allergies/allergies-test.rkt" test)
raco test: 2 (submod "./anagram/anagram-test.rkt" test)
raco test: 0 (submod "./bob/bob-test.rkt" test)
raco test: 3 (submod "./difference-of-squares/difference-of-squares-test.rkt" test)
raco test: 2 (submod "./etl/etl-test.rkt" test)
raco test: 1 (submod "./gigasecond/gigasecond-test.rkt" test)
raco test: 0 (submod "./grains/grains-test.rkt" test)
raco test: 1 (submod "./grep/grep-test.rkt" test)
raco test: 2 (submod "./hamming/hamming-test.rkt" test)
raco test: 0 (submod "./hello-world/hello-world-test.rkt" test)
raco test: 3 (submod "./leap/leap-test.rkt" test)
raco test: 2 (submod "./list-ops/list-ops-test.rkt" test)
raco test: 0 (submod "./nucleotide-count/nucleotide-count-test.rkt" test)
raco test: 3 (submod "./perfect-numbers/perfect-numbers-test.rkt" test)
raco test: 1 (submod "./phone-number/phone-number-test.rkt" test)
raco test: 0 (submod "./raindrops/raindrops-test.rkt" test)
raco test: 4 (submod "./rna-transcription/rna-transcription-test.rkt" test)
raco test: 1 (submod "./roman-numerals/roman-numerals-test.rkt" test)
raco test: 4 (submod "./say/say-test.rkt" test)
raco test: 1 (submod "./word-count/word-count-test.rkt" test)
  42 ./say/say-test.rkt
  30 ./etl/etl-test.rkt
  25 ./allergies/allergies-test.rkt
  25 ./list-ops/list-ops-test.rkt
  18 ./roman-numerals/roman-numerals-test.rkt
  15 ./raindrops/raindrops-test.rkt
  14 ./bob/bob-test.rkt
   9 ./difference-of-squares/difference-of-squares-test.rkt
   8 ./anagram/anagram-test.rkt
   8 ./grains/grains-test.rkt
   8 ./phone-number/phone-number-test.rkt
   8 ./word-count/word-count-test.rkt
   6 ./hamming/hamming-test.rkt
   6 ./rna-transcription/rna-transcription-test.rkt
   5 ./gigasecond/gigasecond-test.rkt
   5 ./leap/leap-test.rkt
   4 ./accumulate/accumulate-test.rkt
   4 ./grep/grep-test.rkt
   4 ./nucleotide-count/nucleotide-count-test.rkt
   4 ./perfect-numbers/perfect-numbers-test.rkt
   2 ./hello-world/hello-world-test.rkt
250 tests passed
```

**Comment by zenspider** [comment]
agreed about the configlet stuff... or at least a `git checkout .; git clean -fd`  before?

**Comment by zenspider** [comment]
@yurrriq I went and changed the cleanup loop to have the same logic as the original loop. I agree that the travis config should probably be checked too.

@kytrinyx this is green now. I'd like official permission to merge from you or someone else before I actually do.

**Comment by yurrriq** [comment]
LGTM

**Comment by mbutterick** [comment]
Can be rewritten using lists instead of hashes, because the value is implied by the position of the key:

```racket
#lang racket

(provide allergic-to? list-allergies)

(define allergies
  '("eggs"
    "peanuts"
    "shellfish"
    "strawberries"
    "tomatoes"
    "chocolate"
    "pollen"
    "cats"))

(define (has-bit? n m)
  (positive? (bitwise-and n m)))

(define (allergic-to? name code)
  (and (member name (list-allergies code)) #t))

(define (list-allergies n)
  (for/list ([(name pos) (in-indexed allergies)]
             #:when (has-bit? (expt 2 pos) n))
            name))
```

**Pull request merged**
