### PR TITLE
Added first pass at scrabble-score for racket.

### PR DESCRIPTION
**Pull request by zenspider**
This is my first contribution to exercism... I read the contributor's doco and was overwhelmed by all the API stuff that doesn't seem relevant? I can't tell. Pushing PR sooner rather than later to get feedback.

### CODE REVIEW

**Comment by yurrriq** [comment]
Hey thanks for the PR! I don't have time to review it now, but naybe @arguello can.

**Comment by kytrinyx** [comment]
Thanks @zenspider—I'm working on a complete overhaul of the documentation. The current docs mix everything together.

**Comment by kytrinyx** [comment]
@exercism/lisp Would one of you have a moment to review this, please?

**Comment by verdammelt** [comment]
I don't know racket so I can't judge it on idiom but it looks pretty good and I like the clarity of the example code.

**Comment by yurrriq** [comment]
LGTM

**Comment by mbutterick** [comment]
FWIW, `match` can be avoided with `case`:

```racket
(define (score word)
  (for/sum ([c (in-string (string-downcase word))]
            #:when (char<=? #\a c #\z))
           (case c
             [(#\a #\e #\i #\o #\u #\l #\n #\r #\s #\t)  1]
             [(#\d #\g)                                  2]
             [(#\b #\c #\m #\p)                          3]
             [(#\f #\h #\v #\w #\y)                      4]
             [(#\k)                                      5]
             [(#\j #\x)                                  8]
             [(#\q #\z)                                 10])))
```

**Pull request merged**
