### PR TITLE
add initial 'exercises' key to config.json (see #58)

### PR DESCRIPTION
**Pull request by cgrayson**
This is just "step 1" from #58, "where difficulty is 1 and topics is empty".

### CODE REVIEW

**Comment by kytrinyx** [comment]
Nice! This looks good to me.

**Comment by yurrriq** [comment]
👍

**Comment by yurrriq** [comment]
Should we remove `"problems"` too or not yet?

**Comment by cgrayson** [comment]
As I understand it, `problems` can't be removed in this track until `exercises` is fully supported and added to all of them.

**Comment by cgrayson** [comment]
No, actually, I don't think that's right, as of [x-api issue 34](https://github.com/exercism/x-api/issues/134). I think `"problems"` _can_ be removed, right @kytrinyx?

**Comment by kytrinyx** [comment]
@cgrayson Yepp, Exercises is now fully supported, with problems only being used if exercises is not present.

**Comment by cgrayson** [comment]
I squashed those commits; can this PR be approved & merged now, or is there anything else I should do?

**Pull request merged**
