### PR TITLE
Reimplement grep and its tests to conform to specification

### LINKED ISSUE #68: Grep tests don't include flags
The tests for the grep exercise don't require the grep function to accept flags, and don't test for them, so it's not adequately testing the spec.

### PR DESCRIPTION
**Pull request by tautologico**
As discussed in #68, the current tests for exercise grep diverge significantly from the common specification: 

- they don't test the use of flags
- they don't test for the possibility of multiple input files

This PR fixes #68 by adapting the tests in the x-common data to racket, and adding an example/reference implementation that passes the tests.

### CODE REVIEW

**Comment by yurrriq** [comment]
Is there a particular reason to use nested `define` forms instead of `let`?

**Comment by zenspider** [comment]
@yurrriq not sure why you're questioning that, considering it's just a reference implementation, but I think the answer is that nested defines are better form:

http://docs.racket-lang.org/style/Choosing_the_Right_Construct.html

**Comment by yurrriq** [comment]
Just curious. I'm mostly a lisper. This looks good to me. Thanks. Let's see if @arguello has any feedback. Otherwise I can merge this and the other PR by Friday.

**Comment by tautologico** [comment]
@yurrriq as @zenspider said, I tried to follow the Racket style guidelines.

**Comment by yurrriq** [comment]
Thanks again, @tautologico!

**Pull request merged**
