### PR TITLE
Test exercises with travis

### PR DESCRIPTION
**Pull request by mbertheau**

### CODE REVIEW

**Comment by yurrriq** [comment]
Can you pull out the `rna-transcription` and `difference-of-squares` changes into a separate PR?

**Comment by mbertheau** [comment]
@yurrriq then the tests fail.

**Comment by yurrriq** [comment]
Hmm. The renaming is part of a larger discussion. I'm cool with this but I'll leave it up to @arguello to merge.

**Comment by arguello** [comment]
looks good.

**Comment by yurrriq** [comment]
@kytrinyx, can you (or someone else with admin privileges, i.e. not me) enable xracket on Travis?

**Comment by kytrinyx** [comment]
Yepp, done!

**Comment by yurrriq** [comment]
Thanks!

**Pull request merged**
